### ISSUE TITLE
Czy kotlin też jest ok?

### ISSUE THREAD

**Issue by emilekm2142** [WieczorekP/Pizza-konkurs#1]
Czy zamiast javy można w kotlinie :tomato:  :joy: ?

**Comment by WieczorekP** [comment]
W zasadzie można w dowolnym języku obiektowym. Będzie wyzwanie też dla mnie bo w życiu nie widziałem linijki kodu w kotlinie :).
Są 2 warunki:
1. Jakiś readme jak to uruchomić i nie ma być to 15 stepów, a zbuduj komendą x odpal x.bat. Ma być porównywalnie prosto jak w szablonie projektu. Nie będę ściągał jakiegoś IDE uruchomić projekt. Ewentualnie możesz dostarczyć repo + skompilowany projekt w jakimś zip'ie i odpalający się na bat czy exe.
2. Ma działać :)


Pozdrawiam
Przemek

**Comment by WieczorekP** [comment]
Skąd dowiedziałeś się o konkursie? Dostaliście jakiś oficjalny mail od uczelni? Nie mogę skontaktować się z dr. Piłką w tej sprawie =\

**Comment by emilekm2142** [comment]
Tak, był mail od Pilki
