### ISSUE TITLE
Ceny i nazwa składnika

### ISSUE THREAD

**Issue by cezary-ptaszek** [WieczorekP/Pizza-konkurs#2]
Wydaje mi się, że:
1) Nie zgadzają się ceny (według cennika składników, z listami(ciasto grube, cienkie)):
NAPOLETANA (16.70 (18.70)),
HAWAJSKA (14.90 (16.90)),
FUNGHI (14.60 (16.60))

2) W pizzy DINAMITE  występuje 'salami pikantne', w składnikach 'salami'.

**Comment by WieczorekP** [comment]
Hej,

Dobrze Ci się wydaje, to celowa zagrywka z mojej strony. Zdarza się że dostajemy od klienta zadanie, które jest niewykonalne z powodu sprzecznych wymagań. Co robimy? Pytamy klienta!! Zawsze, ale to zawsze pytamy klienta, także Twój kodzik dostaje +1 punkt :). Często zdarza się że programiści zgadują, a to prowadzi do poważnych problemów.

Co do samego działania to powinno być ono wyliczane. tj poprawna cena to +50gr w stosunku do menu.

p.s. termin sprawdzania to 21.02.

Pozdrawiam
Przemek

**Comment by cezary-ptaszek** [comment]
Hej,
to tylko NAPOLETANA się w takim razie nie zgadza 0.20zł różnicy :/
Repo ma być publiczne czy dodawać Ciebie do prywatnego?

**Comment by WieczorekP** [comment]
Bez znaczenia. Ważne żebym miał do niego dostęp i zostało zgłoszone przez formularz.
