### ISSUE TITLE
Zniżka 20%

### ISSUE THREAD

**Issue by foxbuur** [WieczorekP/Pizza-konkurs#3]
Zniżka 20% dotyczy całego zamówienia, tj. rabatuje pizzę i dowóz? Czy tylko pizzę, a koszty dowozu pozostają bez zmian?  :) 

BTW rozumiem, że "mozz**e**rella" zamiast "mozzarella" na liście składników, to zwykła literówka? :)

**Comment by WieczorekP** [comment]
1. Zniżka dotyczy całego zamówienia
2. Tak to zwykła literówka.
